MyBasketStats.ClientApp/ViewModels/HomeViewModel.cs
using MyBasketStats.ClientApp.Models;

namespace MyBasketStats.ClientApp.ViewModels
{
    public class HomeViewModel
    {
        public GameDto? Game { get; set; }
    }
}

MyBasketStats.ClientApp/Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
using MyBasketStats.ClientApp.Services;
using MyBasketStats.ClientApp.ViewModels;

namespace MyBasketStats.ClientApp.Controllers
{
    public class GameController : Controller
    {
        private readonly IGameService _gameService;

        public GameController(IGameService gameService)
        {
            _gameService = gameService ??
                throw new ArgumentNullException(nameof(gameService));
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> SearchGame(int id)
        {
            var game = await _gameService.GetGame(id);
            var homeViewModel = new HomeViewModel
            {
                Game = game
            };
            return View("~/Views/Home/Index.cshtml", homeViewModel);
        }
    }
}

MyBasketStats.ClientApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyBasketStats.ClientApp.Models;
using System.Diagnostics;

namespace MyBasketStats.ClientApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyBasketStats.ClientApp/Views/Home/Index.cshtml
@model HomeViewModel?
@if(Model != null)
{
	<partial name="_SearchResult" model="@Model.Game" />
}


	<div class="text-center">
		<h1 class="display-4">Welcome</h1>
		<p>Use this site to search for basketball games.</p>
	</div>
<form asp-controller="Game" asp-action="SearchGame" method="post">
        <label for="id">id:</label>
        <input type="number" name="id" id="id" />
        
        <br />
        <input type="submit" value="Submit" />
</form>